/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { chatCreateStream } from "../../funcs/chatCreateStream.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.CreateChatCompletionStreamRequest$inboundSchema,
};

export const tool$chatCreateStream: ToolDefinition<typeof args> = {
  name: "chat-create-stream",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await chatCreateStream(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
