/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { confidentialChatCreateStream } from "../../funcs/confidentialChatCreateStream.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";
import { decryptMessage } from "../../lib/crypto_utils.js";

const args = {
  request: components.ConfidentialComputeRequest$inboundSchema,
};

export const tool$confidentialChatCreateStream: ToolDefinition<typeof args> = {
  name: "confidential-chat-create-stream",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    // Decrypt the request
    const decryptedData = decryptMessage(
      Buffer.from(args.request.ciphertext, 'base64'),
      Buffer.from(args.request.clientDhPublicKey, 'base64'),
      Buffer.from(args.request.nodeDhPublicKey, 'base64'),
      Buffer.from(args.request.salt, 'base64'),
      Buffer.from(args.request.nonce, 'base64')
    );

    if (!decryptedData) {
      return {
        content: [{ type: "text", text: "Failed to decrypt request" }],
        isError: true,
      };
    }

    const decryptedRequest = JSON.parse(new TextDecoder().decode(decryptedData));
    const stream = await confidentialChatCreateStream(
      client,
      decryptedRequest,
      { fetchOptions: { signal: ctx.signal } },
    );

    return formatResult(stream, {});
  },
};
