/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { confidentialChatCreateStream } from "../../funcs/confidentialChatCreateStream.js";
import * as components from "../../models/components/index.js";
import { ToolDefinition } from "../tools.js";

const args = {
  request: components.CreateChatCompletionRequest$inboundSchema,
};

export const tool$confidentialChatCreateStream: ToolDefinition<typeof args> = {
  name: "confidential-chat-create-stream",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const stream = await confidentialChatCreateStream(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    );

    return {
      content: [{ type: "text", text: "Stream started" }],
      stream,
    };
  },
};
