/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { confidentialImagesGenerate } from "../../funcs/confidentialImagesGenerate.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";
import { decryptMessage } from "../../lib/crypto_utils.js";

const args = {
  request: components.ConfidentialComputeRequest$inboundSchema,
};

export const tool$confidentialImagesGenerate: ToolDefinition<typeof args> = {
  name: "confidential-images-generate",
  description: `Create confidential image

This handler processes image generation requests in a confidential manner, providing additional
encryption and security measures for sensitive data processing. It supports both streaming and
non-streaming responses while maintaining data confidentiality through AEAD encryption and TEE hardware,
for full private AI compute.`,
  args,
  tool: async (client, args, ctx) => {
    // Decrypt the request
    const decryptedData = decryptMessage(
      Buffer.from(args.request.ciphertext, 'base64'),
      Buffer.from(args.request.clientDhPublicKey, 'base64'),
      Buffer.from(args.request.nodeDhPublicKey, 'base64'),
      Buffer.from(args.request.salt, 'base64'),
      Buffer.from(args.request.nonce, 'base64')
    );

    if (!decryptedData) {
      return {
        content: [{ type: "text", text: "Failed to decrypt request" }],
        isError: true,
      };
    }

    const decryptedRequest = JSON.parse(new TextDecoder().decode(decryptedData));
    const result = await confidentialImagesGenerate(
      client,
      decryptedRequest,
      { fetchOptions: { signal: ctx.signal } },
    );

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, {});
  },
};
