/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { imagesGenerate } from "../../funcs/imagesGenerate.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.CreateImageRequest$inboundSchema,
};

export const tool$imagesGenerate: ToolDefinition<typeof args> = {
  name: "images-generate",
  description: `Create image

This endpoint processes requests to generate images using AI models by forwarding them
to the appropriate AI node. The request metadata and compute units have already been
validated by middleware before reaching this handler.

## Errors
* Returns various status codes based on the underlying \`handle_image_generation_response\`:
  - \`INTERNAL_SERVER_ERROR\` - If there's an error communicating with the AI node`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await imagesGenerate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
