/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { modelsOpenRouterModelsList } from "../../funcs/modelsOpenRouterModelsList.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$modelsOpenRouterModelsList: ToolDefinition = {
  name: "models-open-router-models-list",
  description: `OpenRouter models listing endpoint

This endpoint returns a list of available models from the OpenRouter
models file. The file is expected to be in JSON format and contains
information about the models, including their IDs and other metadata.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await modelsOpenRouterModelsList(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
