/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { AtomaSDKCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$chatCreate } from "./tools/chatCreate.js";
import { tool$chatCreateStream } from "./tools/chatCreateStream.js";
import { tool$completionsCreate } from "./tools/completionsCreate.js";
import { tool$completionsCreateStream } from "./tools/completionsCreateStream.js";
import { tool$confidentialChatCreate } from "./tools/confidentialChatCreate.js";
import { tool$confidentialChatCreateStream } from "./tools/confidentialChatCreateStream.js";
import { tool$confidentialCompletionsCreate } from "./tools/confidentialCompletionsCreate.js";
import { tool$confidentialCompletionsCreateStream } from "./tools/confidentialCompletionsCreateStream.js";
import { tool$confidentialEmbeddingsCreate } from "./tools/confidentialEmbeddingsCreate.js";
import { tool$confidentialImagesGenerate } from "./tools/confidentialImagesGenerate.js";
import { tool$embeddingsCreate } from "./tools/embeddingsCreate.js";
import { tool$healthHealth } from "./tools/healthHealth.js";
import { tool$imagesGenerate } from "./tools/imagesGenerate.js";
import { tool$modelsModelsList } from "./tools/modelsModelsList.js";
import { tool$modelsOpenRouterModelsList } from "./tools/modelsOpenRouterModelsList.js";
import { tool$nodesNodesCreate } from "./tools/nodesNodesCreate.js";
import { tool$nodesNodesCreateLock } from "./tools/nodesNodesCreateLock.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  bearerAuth?: SDKOptions["bearerAuth"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "AtomaSDK",
    version: "0.0.2",
  });

  const client = new AtomaSDKCore({
    bearerAuth: deps.bearerAuth,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$completionsCreate);
  tool(tool$completionsCreateStream);
  tool(tool$confidentialCompletionsCreate);
  tool(tool$confidentialCompletionsCreateStream);
  tool(tool$chatCreate);
  tool(tool$chatCreateStream);
  tool(tool$confidentialChatCreate);
  tool(tool$confidentialChatCreateStream);
  tool(tool$confidentialEmbeddingsCreate);
  tool(tool$confidentialImagesGenerate);
  tool(tool$embeddingsCreate);
  tool(tool$healthHealth);
  tool(tool$imagesGenerate);
  tool(tool$modelsModelsList);
  tool(tool$modelsOpenRouterModelsList);
  tool(tool$nodesNodesCreate);
  tool(tool$nodesNodesCreateLock);

  return server;
}
