/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { AtomaSDK } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Confidential Embeddings Confidential Embeddings Create", async () => {
  const testHttpClient = createTestHTTPClient("confidential_embeddings_create");

  const atomaSDK = new AtomaSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearerAuth: process.env["ATOMASDK_BEARER_AUTH"] ?? "value",
  });

  const result = await atomaSDK.confidentialEmbeddings.create({
    input: "The quick brown fox jumps over the lazy dog",
    model: "text-embedding-3-small"
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    object: "list",
    data: [{
      object: "embedding",
      embedding: [0.0023064255, -0.009327292, 0.0023064255],
      index: 0
    }],
    model: "text-embedding-3-small",
    usage: {
      prompt_tokens: 9,
      total_tokens: 9
    }
  });
});
