/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { AtomaSDK } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Confidential Images Confidential Image Generations Create", async () => {
  const testHttpClient = createTestHTTPClient(
    "confidential_image_generations_create",
  );

  const atomaSDK = new AtomaSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearerAuth: process.env["ATOMASDK_BEARER_AUTH"] ?? "value",
  });

  const result = await atomaSDK.confidentialImages.generate({
    prompt: "A beautiful sunset",
    n: 1,
    size: "1024x1024",
    responseFormat: "url",
    model: "dall-e-3"
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    created: 1677652288,
    data: [{
      url: "https://example.com/image.png"
    }]
  });
});
