/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { AtomaSDK } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Images Image Generations Create", async () => {
  const testHttpClient = createTestHTTPClient("image_generations_create");

  const atomaSDK = new AtomaSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearerAuth: process.env["ATOMASDK_BEARER_AUTH"] ?? "value",
  });

  const result = await atomaSDK.images.generate({
    model: "black-forest-labs/FLUX.1-schnell",
    n: 1,
    prompt: "A cute baby sea otter floating on its back",
    quality: "hd",
    responseFormat: "url",
    size: "1024x1024",
    style: "vivid",
    user: "user-1234",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    created: 1677649420,
    data: [
      {
        revisedPrompt:
          "A stunning image of a baby sea otter floating on its back in crystal clear blue water, with gentle ripples surrounding it. The otter's fur appears soft and well-detailed, and its expression is peaceful and content.",
        url:
          "https://oaidalleapiprodscus.blob.core.windows.net/private/image.png",
      },
      {
        revisedPrompt:
          "A stunning image of a baby sea otter floating on its back in crystal clear blue water, with gentle ripples surrounding it. The otter's fur appears soft and well-detailed, and its expression is peaceful and content.",
        url:
          "https://oaidalleapiprodscus.blob.core.windows.net/private/image.png",
      },
    ],
  });
});
