/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { AtomaSDK } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Models Models List", async () => {
  const testHttpClient = createTestHTTPClient("models_list");

  const atomaSDK = new AtomaSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearerAuth: process.env["ATOMASDK_BEARER_AUTH"] ?? "value",
  });

  const result = await atomaSDK.models.modelsList();
  expect(result).toBeDefined();
  expect(result).toEqual({
    data: [
      {
        created: 640785,
        id: "<id>",
        object: "<value>",
        ownedBy: "<value>",
      },
      {
        created: 744692,
        id: "<id>",
        object: "<value>",
        ownedBy: "<value>",
      },
      {
        created: 941970,
        id: "<id>",
        object: "<value>",
        ownedBy: "<value>",
      },
    ],
    object: "<value>",
  });
});

test("Models Open Router Models List", async () => {
  const testHttpClient = createTestHTTPClient("open_router_models_list");

  const atomaSDK = new AtomaSDK({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearerAuth: process.env["ATOMASDK_BEARER_AUTH"] ?? "value",
  });

  const result = await atomaSDK.models.openRouterModelsList();
  expect(result).toBeDefined();
  expect(result).toEqual("<value>");
});
