/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { confidentialEmbeddingsCreate } from "../funcs/confidentialEmbeddingsCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ConfidentialEmbeddings extends ClientSDK {
  /**
   * Create confidential embeddings
   *
   * @remarks
   * This endpoint follows the OpenAI API format for generating vector embeddings from input text,
   * but with confidential processing (through AEAD encryption and TEE hardware).
   * The handler receives pre-processed metadata from middleware and forwards the request to
   * the selected node.
   *
   * ## Returns
   * * `Ok(Response)` - The embeddings response from the processing node
   * * `Err(AtomaProxyError)` - An error status code if any step fails
   *
   * ## Errors
   * * `INTERNAL_SERVER_ERROR` - Processing or node communication failures
   */
  async create(
    request: components.CreateEmbeddingRequest,
    options?: RequestOptions,
  ): Promise<components.CreateEmbeddingResponse> {
    return unwrapAsync(confidentialEmbeddingsCreate(
      this,
      request,
      options,
    ));
  }
}
