/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { healthHealth } from "../funcs/healthHealth.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class Health extends ClientSDK {
  /**
   * Health
   */
  async health(
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(healthHealth(
      this,
      options,
    ));
  }
}
