/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { imagesGenerate } from "../funcs/imagesGenerate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Images extends ClientSDK {
  /**
   * Create image
   *
   * @remarks
   * This endpoint processes requests to generate images using AI models by forwarding them
   * to the appropriate AI node. The request metadata and compute units have already been
   * validated by middleware before reaching this handler.
   *
   * ## Errors
   * * Returns various status codes based on the underlying `handle_image_generation_response`:
   *   - `INTERNAL_SERVER_ERROR` - If there's an error communicating with the AI node
   */
  async generate(
    request: components.CreateImageRequest,
    options?: RequestOptions,
  ): Promise<components.CreateImageResponse> {
    return unwrapAsync(imagesGenerate(
      this,
      request,
      options,
    ));
  }
}
