/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { modelsModelsList } from "../funcs/modelsModelsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Models extends ClientSDK {
  /**
   * List models
   *
   * @remarks
   * This endpoint mimics the OpenAI models endpoint format, returning a list of
   * available models with their associated metadata. Each model includes standard
   * OpenAI-compatible fields to ensure compatibility with existing OpenAI client libraries.
   */
  async modelsList(
    options?: RequestOptions,
  ): Promise<components.ModelList> {
    return unwrapAsync(modelsModelsList(
      this,
      options,
    ));
  }
}
