/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { modelsModelsHandler } from "../funcs/modelsModelsHandler.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class Models extends ClientSDK {
  /**
   * List models
   *
   * @remarks
   * This endpoint mimics the OpenAI models endpoint format, returning a list of
   * available models with their associated metadata and permissions. Each model
   * includes standard OpenAI-compatible fields to ensure compatibility with
   * existing OpenAI client libraries.
   */
  async modelsHandler(
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(modelsModelsHandler(
      this,
      options,
    ));
  }
}
