workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    atoma-proxy:
        inputs:
            - location: ../atoma-proxy/atoma-proxy/docs/openapi.yml
        registry:
            location: registry.speakeasyapi.dev/atoma/atoma-sdk/atoma-proxy
targets:
    atoma-sdk:
        target: typescript
        source: atoma-proxy
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/atoma/atoma-sdk/atoma-proxy-typescript-code-samples
            blocking: false
