workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    atoma-proxy:
        inputs:
            - location: ../atoma-proxy/atoma-proxy/docs/openapi.yml
        registry:
            location: registry.speakeasyapi.dev/atoma/test/atoma-proxy
targets:
    atoma-sdk:
        target: typescript
        source: atoma-proxy
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/atoma/test/atoma-proxy-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
        testing:
            enabled: true
