/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Chat completions
 */
export type ConfidentialCompletionsCreateStreamResponseBody = {
  /**
   * Represents a response from a confidential compute request
   */
  data: components.ConfidentialComputeStreamResponse;
};

/** @internal */
export const ConfidentialCompletionsCreateStreamResponseBody$inboundSchema:
  z.ZodType<
    ConfidentialCompletionsCreateStreamResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.string().transform((v, ctx) => {
      try {
        return JSON.parse(v);
      } catch (err) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: `malformed json: ${err}`,
        });
        return z.NEVER;
      }
    }).pipe(components.ConfidentialComputeStreamResponse$inboundSchema),
  });

/** @internal */
export type ConfidentialCompletionsCreateStreamResponseBody$Outbound = {
  data: components.ConfidentialComputeStreamResponse$Outbound;
};

/** @internal */
export const ConfidentialCompletionsCreateStreamResponseBody$outboundSchema:
  z.ZodType<
    ConfidentialCompletionsCreateStreamResponseBody$Outbound,
    z.ZodTypeDef,
    ConfidentialCompletionsCreateStreamResponseBody
  > = z.object({
    data: components.ConfidentialComputeStreamResponse$outboundSchema,
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConfidentialCompletionsCreateStreamResponseBody$ {
  /** @deprecated use `ConfidentialCompletionsCreateStreamResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    ConfidentialCompletionsCreateStreamResponseBody$inboundSchema;
  /** @deprecated use `ConfidentialCompletionsCreateStreamResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    ConfidentialCompletionsCreateStreamResponseBody$outboundSchema;
  /** @deprecated use `ConfidentialCompletionsCreateStreamResponseBody$Outbound` instead. */
  export type Outbound =
    ConfidentialCompletionsCreateStreamResponseBody$Outbound;
}

export function confidentialCompletionsCreateStreamResponseBodyToJSON(
  confidentialCompletionsCreateStreamResponseBody:
    ConfidentialCompletionsCreateStreamResponseBody,
): string {
  return JSON.stringify(
    ConfidentialCompletionsCreateStreamResponseBody$outboundSchema.parse(
      confidentialCompletionsCreateStreamResponseBody,
    ),
  );
}

export function confidentialCompletionsCreateStreamResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  ConfidentialCompletionsCreateStreamResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ConfidentialCompletionsCreateStreamResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ConfidentialCompletionsCreateStreamResponseBody' from JSON`,
  );
}
