/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ChatCompletionChoice,
  ChatCompletionChoice$inboundSchema,
  ChatCompletionChoice$Outbound,
  ChatCompletionChoice$outboundSchema,
} from "./chatcompletionchoice.js";
import {
  CompletionUsage,
  CompletionUsage$inboundSchema,
  CompletionUsage$Outbound,
  CompletionUsage$outboundSchema,
} from "./completionusage.js";

export type ChatCompletionResponse = {
  /**
   * A list of chat completion choices.
   */
  choices: Array<ChatCompletionChoice>;
  /**
   * The Unix timestamp (in seconds) of when the chat completion was created.
   */
  created: number;
  /**
   * A unique identifier for the chat completion.
   */
  id: string;
  /**
   * The model used for the chat completion.
   */
  model: string;
  /**
   * The system fingerprint for the completion, if applicable.
   */
  systemFingerprint?: string | null | undefined;
  usage?: CompletionUsage | null | undefined;
};

/** @internal */
export const ChatCompletionResponse$inboundSchema: z.ZodType<
  ChatCompletionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  choices: z.array(ChatCompletionChoice$inboundSchema),
  created: z.number().int(),
  id: z.string(),
  model: z.string(),
  system_fingerprint: z.nullable(z.string()).optional(),
  usage: z.nullable(CompletionUsage$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "system_fingerprint": "systemFingerprint",
  });
});

/** @internal */
export type ChatCompletionResponse$Outbound = {
  choices: Array<ChatCompletionChoice$Outbound>;
  created: number;
  id: string;
  model: string;
  system_fingerprint?: string | null | undefined;
  usage?: CompletionUsage$Outbound | null | undefined;
};

/** @internal */
export const ChatCompletionResponse$outboundSchema: z.ZodType<
  ChatCompletionResponse$Outbound,
  z.ZodTypeDef,
  ChatCompletionResponse
> = z.object({
  choices: z.array(ChatCompletionChoice$outboundSchema),
  created: z.number().int(),
  id: z.string(),
  model: z.string(),
  systemFingerprint: z.nullable(z.string()).optional(),
  usage: z.nullable(CompletionUsage$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    systemFingerprint: "system_fingerprint",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChatCompletionResponse$ {
  /** @deprecated use `ChatCompletionResponse$inboundSchema` instead. */
  export const inboundSchema = ChatCompletionResponse$inboundSchema;
  /** @deprecated use `ChatCompletionResponse$outboundSchema` instead. */
  export const outboundSchema = ChatCompletionResponse$outboundSchema;
  /** @deprecated use `ChatCompletionResponse$Outbound` instead. */
  export type Outbound = ChatCompletionResponse$Outbound;
}

export function chatCompletionResponseToJSON(
  chatCompletionResponse: ChatCompletionResponse,
): string {
  return JSON.stringify(
    ChatCompletionResponse$outboundSchema.parse(chatCompletionResponse),
  );
}

export function chatCompletionResponseFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionResponse' from JSON`,
  );
}
