/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ChatCompletionChunkDeltaToolCall,
  ChatCompletionChunkDeltaToolCall$inboundSchema,
  ChatCompletionChunkDeltaToolCall$Outbound,
  ChatCompletionChunkDeltaToolCall$outboundSchema,
} from "./chatcompletionchunkdeltatoolcall.js";

/**
 * Represents the chat completion chunk delta.
 *
 * @remarks
 *
 * This is used to represent the chat completion chunk delta in the chat completion request.
 * It can be either a chat completion chunk delta message or a chat completion chunk delta choice.
 */
export type ChatCompletionChunkDelta = {
  /**
   * The content of the message, if present in this chunk.
   */
  content?: string | null | undefined;
  /**
   * The reasoning content, if present in this chunk.
   */
  reasoningContent?: string | null | undefined;
  /**
   * The role of the message author, if present in this chunk.
   */
  role?: string | null | undefined;
  /**
   * The tool calls information, if present in this chunk.
   */
  toolCalls?: Array<ChatCompletionChunkDeltaToolCall> | null | undefined;
};

/** @internal */
export const ChatCompletionChunkDelta$inboundSchema: z.ZodType<
  ChatCompletionChunkDelta,
  z.ZodTypeDef,
  unknown
> = z.object({
  content: z.nullable(z.string()).optional(),
  reasoning_content: z.nullable(z.string()).optional(),
  role: z.nullable(z.string()).optional(),
  tool_calls: z.nullable(
    z.array(ChatCompletionChunkDeltaToolCall$inboundSchema),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "reasoning_content": "reasoningContent",
    "tool_calls": "toolCalls",
  });
});

/** @internal */
export type ChatCompletionChunkDelta$Outbound = {
  content?: string | null | undefined;
  reasoning_content?: string | null | undefined;
  role?: string | null | undefined;
  tool_calls?:
    | Array<ChatCompletionChunkDeltaToolCall$Outbound>
    | null
    | undefined;
};

/** @internal */
export const ChatCompletionChunkDelta$outboundSchema: z.ZodType<
  ChatCompletionChunkDelta$Outbound,
  z.ZodTypeDef,
  ChatCompletionChunkDelta
> = z.object({
  content: z.nullable(z.string()).optional(),
  reasoningContent: z.nullable(z.string()).optional(),
  role: z.nullable(z.string()).optional(),
  toolCalls: z.nullable(
    z.array(ChatCompletionChunkDeltaToolCall$outboundSchema),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    reasoningContent: "reasoning_content",
    toolCalls: "tool_calls",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChatCompletionChunkDelta$ {
  /** @deprecated use `ChatCompletionChunkDelta$inboundSchema` instead. */
  export const inboundSchema = ChatCompletionChunkDelta$inboundSchema;
  /** @deprecated use `ChatCompletionChunkDelta$outboundSchema` instead. */
  export const outboundSchema = ChatCompletionChunkDelta$outboundSchema;
  /** @deprecated use `ChatCompletionChunkDelta$Outbound` instead. */
  export type Outbound = ChatCompletionChunkDelta$Outbound;
}

export function chatCompletionChunkDeltaToJSON(
  chatCompletionChunkDelta: ChatCompletionChunkDelta,
): string {
  return JSON.stringify(
    ChatCompletionChunkDelta$outboundSchema.parse(chatCompletionChunkDelta),
  );
}

export function chatCompletionChunkDeltaFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionChunkDelta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionChunkDelta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionChunkDelta' from JSON`,
  );
}
