/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CompletionChoice,
  CompletionChoice$inboundSchema,
  CompletionChoice$Outbound,
  CompletionChoice$outboundSchema,
} from "./completionchoice.js";
import {
  Usage,
  Usage$inboundSchema,
  Usage$Outbound,
  Usage$outboundSchema,
} from "./usage.js";

export type CompletionsResponse = {
  /**
   * Array of completion choices response
   */
  choices: Array<CompletionChoice>;
  /**
   * The creation time of the request
   */
  created: number;
  /**
   * The ID of the request
   */
  id: string;
  /**
   * The model used for the request
   */
  model: string;
  /**
   * The object type
   */
  object: string;
  /**
   * The system fingerprint
   */
  systemFingerprint: string;
  usage: Usage;
};

/** @internal */
export const CompletionsResponse$inboundSchema: z.ZodType<
  CompletionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  choices: z.array(CompletionChoice$inboundSchema),
  created: z.number().int(),
  id: z.string(),
  model: z.string(),
  object: z.string(),
  system_fingerprint: z.string(),
  usage: Usage$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "system_fingerprint": "systemFingerprint",
  });
});

/** @internal */
export type CompletionsResponse$Outbound = {
  choices: Array<CompletionChoice$Outbound>;
  created: number;
  id: string;
  model: string;
  object: string;
  system_fingerprint: string;
  usage: Usage$Outbound;
};

/** @internal */
export const CompletionsResponse$outboundSchema: z.ZodType<
  CompletionsResponse$Outbound,
  z.ZodTypeDef,
  CompletionsResponse
> = z.object({
  choices: z.array(CompletionChoice$outboundSchema),
  created: z.number().int(),
  id: z.string(),
  model: z.string(),
  object: z.string(),
  systemFingerprint: z.string(),
  usage: Usage$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    systemFingerprint: "system_fingerprint",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CompletionsResponse$ {
  /** @deprecated use `CompletionsResponse$inboundSchema` instead. */
  export const inboundSchema = CompletionsResponse$inboundSchema;
  /** @deprecated use `CompletionsResponse$outboundSchema` instead. */
  export const outboundSchema = CompletionsResponse$outboundSchema;
  /** @deprecated use `CompletionsResponse$Outbound` instead. */
  export type Outbound = CompletionsResponse$Outbound;
}

export function completionsResponseToJSON(
  completionsResponse: CompletionsResponse,
): string {
  return JSON.stringify(
    CompletionsResponse$outboundSchema.parse(completionsResponse),
  );
}

export function completionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<CompletionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompletionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompletionsResponse' from JSON`,
  );
}
