/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The details of the completion tokens
 */
export type CompletionTokensDetails = {
  /**
   * The number of tokens in the completion
   */
  acceptedPredictionTokens?: number | null | undefined;
  /**
   * The number of audio tokens
   */
  audioTokens?: number | null | undefined;
  /**
   * The number of reasoning tokens
   */
  reasoningTokens?: number | null | undefined;
  /**
   * The number of rejected prediction tokens
   */
  rejectedPredictionTokens?: number | null | undefined;
};

/** @internal */
export const CompletionTokensDetails$inboundSchema: z.ZodType<
  CompletionTokensDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  accepted_prediction_tokens: z.number().int().optional().nullable(),
  audio_tokens: z.number().int().optional().nullable(),
  reasoning_tokens: z.number().int().optional().nullable(),
  rejected_prediction_tokens: z.number().int().optional().nullable(),
}).transform((v) => {
  return remap$(v, {
    "accepted_prediction_tokens": "acceptedPredictionTokens",
    "audio_tokens": "audioTokens",
    "reasoning_tokens": "reasoningTokens",
    "rejected_prediction_tokens": "rejectedPredictionTokens",
  });
});

/** @internal */
export type CompletionTokensDetails$Outbound = {
  accepted_prediction_tokens?: number | null | undefined;
  audio_tokens?: number | null | undefined;
  reasoning_tokens?: number | null | undefined;
  rejected_prediction_tokens?: number | null | undefined;
};

/** @internal */
export const CompletionTokensDetails$outboundSchema: z.ZodType<
  CompletionTokensDetails$Outbound,
  z.ZodTypeDef,
  CompletionTokensDetails
> = z.object({
  acceptedPredictionTokens: z.number().int().optional().nullable(),
  audioTokens: z.number().int().optional().nullable(),
  reasoningTokens: z.number().int().optional().nullable(),
  rejectedPredictionTokens: z.number().int().optional().nullable(),
}).transform((v) => {
  return remap$(v, {
    acceptedPredictionTokens: "accepted_prediction_tokens",
    audioTokens: "audio_tokens",
    reasoningTokens: "reasoning_tokens",
    rejectedPredictionTokens: "rejected_prediction_tokens",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CompletionTokensDetails$ {
  /** @deprecated use `CompletionTokensDetails$inboundSchema` instead. */
  export const inboundSchema = CompletionTokensDetails$inboundSchema;
  /** @deprecated use `CompletionTokensDetails$outboundSchema` instead. */
  export const outboundSchema = CompletionTokensDetails$outboundSchema;
  /** @deprecated use `CompletionTokensDetails$Outbound` instead. */
  export type Outbound = CompletionTokensDetails$Outbound;
}

export function completionTokensDetailsToJSON(
  completionTokensDetails: CompletionTokensDetails,
): string {
  return JSON.stringify(
    CompletionTokensDetails$outboundSchema.parse(completionTokensDetails),
  );
}

export function completionTokensDetailsFromJSON(
  jsonString: string,
): SafeParseResult<CompletionTokensDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompletionTokensDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompletionTokensDetails' from JSON`,
  );
}
