/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  LogProbs,
  LogProbs$inboundSchema,
  LogProbs$Outbound,
  LogProbs$outboundSchema,
} from "./logprobs.js";

/**
 * A completion choice response
 */
export type CompletionChoice = {
  /**
   * The reason the model stopped generating tokens
   */
  finishReason: string;
  /**
   * The index of the choice in the list of choices
   */
  index: number;
  logprobs?: LogProbs | null | undefined;
  /**
   * The generated text
   */
  text: string;
};

/** @internal */
export const CompletionChoice$inboundSchema: z.ZodType<
  CompletionChoice,
  z.ZodTypeDef,
  unknown
> = z.object({
  finish_reason: z.string(),
  index: z.number().int(),
  logprobs: z.nullable(LogProbs$inboundSchema).optional(),
  text: z.string(),
}).transform((v) => {
  return remap$(v, {
    "finish_reason": "finishReason",
  });
});

/** @internal */
export type CompletionChoice$Outbound = {
  finish_reason: string;
  index: number;
  logprobs?: LogProbs$Outbound | null | undefined;
  text: string;
};

/** @internal */
export const CompletionChoice$outboundSchema: z.ZodType<
  CompletionChoice$Outbound,
  z.ZodTypeDef,
  CompletionChoice
> = z.object({
  finishReason: z.string(),
  index: z.number().int(),
  logprobs: z.nullable(LogProbs$outboundSchema).optional(),
  text: z.string(),
}).transform((v) => {
  return remap$(v, {
    finishReason: "finish_reason",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CompletionChoice$ {
  /** @deprecated use `CompletionChoice$inboundSchema` instead. */
  export const inboundSchema = CompletionChoice$inboundSchema;
  /** @deprecated use `CompletionChoice$outboundSchema` instead. */
  export const outboundSchema = CompletionChoice$outboundSchema;
  /** @deprecated use `CompletionChoice$Outbound` instead. */
  export type Outbound = CompletionChoice$Outbound;
}

export function completionChoiceToJSON(
  completionChoice: CompletionChoice,
): string {
  return JSON.stringify(
    CompletionChoice$outboundSchema.parse(completionChoice),
  );
}

export function completionChoiceFromJSON(
  jsonString: string,
): SafeParseResult<CompletionChoice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompletionChoice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompletionChoice' from JSON`,
  );
}
