/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CompletionsPrompt =
  | string
  | Array<string>
  | Array<number>
  | Array<Array<number>>;

/** @internal */
export const CompletionsPrompt$inboundSchema: z.ZodType<
  CompletionsPrompt,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.array(z.string()),
  z.array(z.number().int()),
  z.array(z.array(z.number().int())),
]);

/** @internal */
export type CompletionsPrompt$Outbound =
  | string
  | Array<string>
  | Array<number>
  | Array<Array<number>>;

/** @internal */
export const CompletionsPrompt$outboundSchema: z.ZodType<
  CompletionsPrompt$Outbound,
  z.ZodTypeDef,
  CompletionsPrompt
> = z.union([
  z.string(),
  z.array(z.string()),
  z.array(z.number().int()),
  z.array(z.array(z.number().int())),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CompletionsPrompt$ {
  /** @deprecated use `CompletionsPrompt$inboundSchema` instead. */
  export const inboundSchema = CompletionsPrompt$inboundSchema;
  /** @deprecated use `CompletionsPrompt$outboundSchema` instead. */
  export const outboundSchema = CompletionsPrompt$outboundSchema;
  /** @deprecated use `CompletionsPrompt$Outbound` instead. */
  export type Outbound = CompletionsPrompt$Outbound;
}

export function completionsPromptToJSON(
  completionsPrompt: CompletionsPrompt,
): string {
  return JSON.stringify(
    CompletionsPrompt$outboundSchema.parse(completionsPrompt),
  );
}

export function completionsPromptFromJSON(
  jsonString: string,
): SafeParseResult<CompletionsPrompt, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompletionsPrompt$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompletionsPrompt' from JSON`,
  );
}
