/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Usage information for the embeddings request
 */
export type EmbeddingUsage = {
  /**
   * Number of tokens in the prompt
   */
  promptTokens: number;
  /**
   * Total tokens used in the request
   */
  totalTokens: number;
};

/** @internal */
export const EmbeddingUsage$inboundSchema: z.ZodType<
  EmbeddingUsage,
  z.ZodTypeDef,
  unknown
> = z.object({
  prompt_tokens: z.number().int(),
  total_tokens: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "prompt_tokens": "promptTokens",
    "total_tokens": "totalTokens",
  });
});

/** @internal */
export type EmbeddingUsage$Outbound = {
  prompt_tokens: number;
  total_tokens: number;
};

/** @internal */
export const EmbeddingUsage$outboundSchema: z.ZodType<
  EmbeddingUsage$Outbound,
  z.ZodTypeDef,
  EmbeddingUsage
> = z.object({
  promptTokens: z.number().int(),
  totalTokens: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    promptTokens: "prompt_tokens",
    totalTokens: "total_tokens",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EmbeddingUsage$ {
  /** @deprecated use `EmbeddingUsage$inboundSchema` instead. */
  export const inboundSchema = EmbeddingUsage$inboundSchema;
  /** @deprecated use `EmbeddingUsage$outboundSchema` instead. */
  export const outboundSchema = EmbeddingUsage$outboundSchema;
  /** @deprecated use `EmbeddingUsage$Outbound` instead. */
  export type Outbound = EmbeddingUsage$Outbound;
}

export function embeddingUsageToJSON(embeddingUsage: EmbeddingUsage): string {
  return JSON.stringify(EmbeddingUsage$outboundSchema.parse(embeddingUsage));
}

export function embeddingUsageFromJSON(
  jsonString: string,
): SafeParseResult<EmbeddingUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmbeddingUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmbeddingUsage' from JSON`,
  );
}
