/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EmbeddingInput = string | Array<string>;

/** @internal */
export const EmbeddingInput$inboundSchema: z.ZodType<
  EmbeddingInput,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.array(z.string())]);

/** @internal */
export type EmbeddingInput$Outbound = string | Array<string>;

/** @internal */
export const EmbeddingInput$outboundSchema: z.ZodType<
  EmbeddingInput$Outbound,
  z.ZodTypeDef,
  EmbeddingInput
> = z.union([z.string(), z.array(z.string())]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EmbeddingInput$ {
  /** @deprecated use `EmbeddingInput$inboundSchema` instead. */
  export const inboundSchema = EmbeddingInput$inboundSchema;
  /** @deprecated use `EmbeddingInput$outboundSchema` instead. */
  export const outboundSchema = EmbeddingInput$outboundSchema;
  /** @deprecated use `EmbeddingInput$Outbound` instead. */
  export type Outbound = EmbeddingInput$Outbound;
}

export function embeddingInputToJSON(embeddingInput: EmbeddingInput): string {
  return JSON.stringify(EmbeddingInput$outboundSchema.parse(embeddingInput));
}

export function embeddingInputFromJSON(
  jsonString: string,
): SafeParseResult<EmbeddingInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmbeddingInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmbeddingInput' from JSON`,
  );
}
