/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The response body for selecting a node's public key for encryption
 *
 * @remarks
 * from a client. The client will use the provided public key to encrypt
 * the request and send it back to the proxy. The proxy will then route this
 * request to the selected node.
 */
export type NodesModelsRetrieveResponse = {
  /**
   * The node small id for the selected node
   */
  nodeSmallId: number;
  /**
   * The public key for the selected node, base64 encoded
   */
  publicKey: Array<number>;
  /**
   * Transaction digest for the transaction that acquires the stack entry, if any
   */
  stackEntryDigest?: string | null | undefined;
  /**
   * The stack small id to which an available stack entry was acquired, for the selected node
   */
  stackSmallId: number;
};

/** @internal */
export const NodesModelsRetrieveResponse$inboundSchema: z.ZodType<
  NodesModelsRetrieveResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  node_small_id: z.number().int(),
  public_key: z.array(z.number().int()),
  stack_entry_digest: z.nullable(z.string()).optional(),
  stack_small_id: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "node_small_id": "nodeSmallId",
    "public_key": "publicKey",
    "stack_entry_digest": "stackEntryDigest",
    "stack_small_id": "stackSmallId",
  });
});

/** @internal */
export type NodesModelsRetrieveResponse$Outbound = {
  node_small_id: number;
  public_key: Array<number>;
  stack_entry_digest?: string | null | undefined;
  stack_small_id: number;
};

/** @internal */
export const NodesModelsRetrieveResponse$outboundSchema: z.ZodType<
  NodesModelsRetrieveResponse$Outbound,
  z.ZodTypeDef,
  NodesModelsRetrieveResponse
> = z.object({
  nodeSmallId: z.number().int(),
  publicKey: z.array(z.number().int()),
  stackEntryDigest: z.nullable(z.string()).optional(),
  stackSmallId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    nodeSmallId: "node_small_id",
    publicKey: "public_key",
    stackEntryDigest: "stack_entry_digest",
    stackSmallId: "stack_small_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NodesModelsRetrieveResponse$ {
  /** @deprecated use `NodesModelsRetrieveResponse$inboundSchema` instead. */
  export const inboundSchema = NodesModelsRetrieveResponse$inboundSchema;
  /** @deprecated use `NodesModelsRetrieveResponse$outboundSchema` instead. */
  export const outboundSchema = NodesModelsRetrieveResponse$outboundSchema;
  /** @deprecated use `NodesModelsRetrieveResponse$Outbound` instead. */
  export type Outbound = NodesModelsRetrieveResponse$Outbound;
}

export function nodesModelsRetrieveResponseToJSON(
  nodesModelsRetrieveResponse: NodesModelsRetrieveResponse,
): string {
  return JSON.stringify(
    NodesModelsRetrieveResponse$outboundSchema.parse(
      nodesModelsRetrieveResponse,
    ),
  );
}

export function nodesModelsRetrieveResponseFromJSON(
  jsonString: string,
): SafeParseResult<NodesModelsRetrieveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NodesModelsRetrieveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NodesModelsRetrieveResponse' from JSON`,
  );
}
