/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Request body for creating a node lock
 */
export type NodesCreateLockRequest = {
  /**
   * The model to lock a node for
   */
  model: string;
  /**
   * The maximum number of tokens that can be locked for the node
   */
  maxNumberOfTokens?: number;

  /**
   * The time the lock will be active for
   */
  timeout?: number;
};

/** @internal */
export const NodesCreateLockRequest$inboundSchema: z.ZodType<
  NodesCreateLockRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  model: z.string(),
  maxNumberOfTokens: z.number().optional().default(0),
  timeout: z.number().optional().default(0),
});

/** @internal */
export type NodesCreateLockRequest$Outbound = {
  model: string;
};

/** @internal */
export const NodesCreateLockRequest$outboundSchema: z.ZodType<
  NodesCreateLockRequest$Outbound,
  z.ZodTypeDef,
  NodesCreateLockRequest
> = z.object({
  model: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NodesCreateLockRequest$ {
  /** @deprecated use `NodesCreateLockRequest$inboundSchema` instead. */
  export const inboundSchema = NodesCreateLockRequest$inboundSchema;
  /** @deprecated use `NodesCreateLockRequest$outboundSchema` instead. */
  export const outboundSchema = NodesCreateLockRequest$outboundSchema;
  /** @deprecated use `NodesCreateLockRequest$Outbound` instead. */
  export type Outbound = NodesCreateLockRequest$Outbound;
}

export function nodesCreateLockRequestToJSON(
  nodesCreateLockRequest: NodesCreateLockRequest,
): string {
  return JSON.stringify(
    NodesCreateLockRequest$outboundSchema.parse(nodesCreateLockRequest),
  );
}

export function nodesCreateLockRequestFromJSON(
  jsonString: string,
): SafeParseResult<NodesCreateLockRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NodesCreateLockRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NodesCreateLockRequest' from JSON`,
  );
}
