/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The format to return the response in.
 */
export const ResponseFormatType = {
  Text: "text",
  JsonObject: "json_object",
  JsonSchema: "json_schema",
} as const;
/**
 * The format to return the response in.
 */
export type ResponseFormatType = ClosedEnum<typeof ResponseFormatType>;

/** @internal */
export const ResponseFormatType$inboundSchema: z.ZodNativeEnum<
  typeof ResponseFormatType
> = z.nativeEnum(ResponseFormatType);

/** @internal */
export const ResponseFormatType$outboundSchema: z.ZodNativeEnum<
  typeof ResponseFormatType
> = ResponseFormatType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponseFormatType$ {
  /** @deprecated use `ResponseFormatType$inboundSchema` instead. */
  export const inboundSchema = ResponseFormatType$inboundSchema;
  /** @deprecated use `ResponseFormatType$outboundSchema` instead. */
  export const outboundSchema = ResponseFormatType$outboundSchema;
}
