/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * A literal tool choice that can be used in a chat completion.
 *
 * @remarks
 *
 * This is used to represent the literal tool choice in the chat completion request.
 * It can be either none or auto.
 */
export const ToolChoiceLiteral = {
  None: "none",
  Auto: "auto",
} as const;
/**
 * A literal tool choice that can be used in a chat completion.
 *
 * @remarks
 *
 * This is used to represent the literal tool choice in the chat completion request.
 * It can be either none or auto.
 */
export type ToolChoiceLiteral = ClosedEnum<typeof ToolChoiceLiteral>;

/** @internal */
export const ToolChoiceLiteral$inboundSchema: z.ZodNativeEnum<
  typeof ToolChoiceLiteral
> = z.nativeEnum(ToolChoiceLiteral);

/** @internal */
export const ToolChoiceLiteral$outboundSchema: z.ZodNativeEnum<
  typeof ToolChoiceLiteral
> = ToolChoiceLiteral$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ToolChoiceLiteral$ {
  /** @deprecated use `ToolChoiceLiteral$inboundSchema` instead. */
  export const inboundSchema = ToolChoiceLiteral$inboundSchema;
  /** @deprecated use `ToolChoiceLiteral$outboundSchema` instead. */
  export const outboundSchema = ToolChoiceLiteral$outboundSchema;
}
