/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Represents usage statistics for a confidential compute request
 */
export type Usage = {
  /**
   * Number of compute units used
   *
   * @remarks
   * NOTE: This is not used for the embeddings endpoint
   */
  completionTokens?: number | null | undefined;
  /**
   * Details about the completion tokens
   */
  completionTokensDetails?: any | undefined;
  /**
   * Number of compute units used
   */
  promptTokens: number;
  /**
   * Number of compute units used
   */
  totalTokens: number;
};

/** @internal */
export const Usage$inboundSchema: z.ZodType<Usage, z.ZodTypeDef, unknown> = z
  .object({
    completion_tokens: z.nullable(z.number().int()).optional(),
    completion_tokens_details: z.any().optional(),
    prompt_tokens: z.number().int(),
    total_tokens: z.number().int(),
  }).transform((v) => {
    return remap$(v, {
      "completion_tokens": "completionTokens",
      "completion_tokens_details": "completionTokensDetails",
      "prompt_tokens": "promptTokens",
      "total_tokens": "totalTokens",
    });
  });

/** @internal */
export type Usage$Outbound = {
  completion_tokens?: number | null | undefined;
  completion_tokens_details?: any | undefined;
  prompt_tokens: number;
  total_tokens: number;
};

/** @internal */
export const Usage$outboundSchema: z.ZodType<
  Usage$Outbound,
  z.ZodTypeDef,
  Usage
> = z.object({
  completionTokens: z.nullable(z.number().int()).optional(),
  completionTokensDetails: z.any().optional(),
  promptTokens: z.number().int(),
  totalTokens: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    completionTokens: "completion_tokens",
    completionTokensDetails: "completion_tokens_details",
    promptTokens: "prompt_tokens",
    totalTokens: "total_tokens",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Usage$ {
  /** @deprecated use `Usage$inboundSchema` instead. */
  export const inboundSchema = Usage$inboundSchema;
  /** @deprecated use `Usage$outboundSchema` instead. */
  export const outboundSchema = Usage$outboundSchema;
  /** @deprecated use `Usage$Outbound` instead. */
  export type Outbound = Usage$Outbound;
}

export function usageToJSON(usage: Usage): string {
  return JSON.stringify(Usage$outboundSchema.parse(usage));
}

export function usageFromJSON(
  jsonString: string,
): SafeParseResult<Usage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Usage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Usage' from JSON`,
  );
}
