/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CompletionTokensDetails,
  CompletionTokensDetails$inboundSchema,
  CompletionTokensDetails$Outbound,
  CompletionTokensDetails$outboundSchema,
} from "./completiontokensdetails.js";
import {
  PromptTokensDetails,
  PromptTokensDetails$inboundSchema,
  PromptTokensDetails$Outbound,
  PromptTokensDetails$outboundSchema,
} from "./prompttokensdetails.js";

export type Usage = {
  /**
   * The number of completion tokens used
   */
  completionTokens: number;
  /**
   * The details of the completion tokens
   */
  completionTokensDetails: CompletionTokensDetails;
  /**
   * The number of prompt tokens used
   */
  promptTokens: number;
  promptTokensDetails: PromptTokensDetails;
  /**
   * The total number of tokens used
   */
  totalTokens: number;
};

/** @internal */
export const Usage$inboundSchema: z.ZodType<Usage, z.ZodTypeDef, unknown> = z
  .object({
    completion_tokens: z.number().int(),
    completion_tokens_details: CompletionTokensDetails$inboundSchema,
    prompt_tokens: z.number().int(),
    prompt_tokens_details: PromptTokensDetails$inboundSchema,
    total_tokens: z.number().int(),
  }).transform((v) => {
    return remap$(v, {
      "completion_tokens": "completionTokens",
      "completion_tokens_details": "completionTokensDetails",
      "prompt_tokens": "promptTokens",
      "prompt_tokens_details": "promptTokensDetails",
      "total_tokens": "totalTokens",
    });
  });

/** @internal */
export type Usage$Outbound = {
  completion_tokens: number;
  completion_tokens_details: CompletionTokensDetails$Outbound;
  prompt_tokens: number;
  prompt_tokens_details: PromptTokensDetails$Outbound;
  total_tokens: number;
};

/** @internal */
export const Usage$outboundSchema: z.ZodType<
  Usage$Outbound,
  z.ZodTypeDef,
  Usage
> = z.object({
  completionTokens: z.number().int(),
  completionTokensDetails: CompletionTokensDetails$outboundSchema,
  promptTokens: z.number().int(),
  promptTokensDetails: PromptTokensDetails$outboundSchema,
  totalTokens: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    completionTokens: "completion_tokens",
    completionTokensDetails: "completion_tokens_details",
    promptTokens: "prompt_tokens",
    promptTokensDetails: "prompt_tokens_details",
    totalTokens: "total_tokens",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Usage$ {
  /** @deprecated use `Usage$inboundSchema` instead. */
  export const inboundSchema = Usage$inboundSchema;
  /** @deprecated use `Usage$outboundSchema` instead. */
  export const outboundSchema = Usage$outboundSchema;
  /** @deprecated use `Usage$Outbound` instead. */
  export type Outbound = Usage$Outbound;
}

export function usageToJSON(usage: Usage): string {
  return JSON.stringify(Usage$outboundSchema.parse(usage));
}

export function usageFromJSON(
  jsonString: string,
): SafeParseResult<Usage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Usage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Usage' from JSON`,
  );
}
